DROP TABLE IF EXISTS hr_indicators;
DROP TABLE IF EXISTS responses;
DROP TABLE IF EXISTS totens;
DROP TABLE IF EXISTS shifts;
DROP TABLE IF EXISTS user_sectors;
DROP TABLE IF EXISTS sectors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS units;
